### ISSUE TITLE
Incorrect results

### ISSUE THREAD

**Issue by svegaxmr** [walleth/keccak#4] opened 2018-06-01 21:15 UTC
For 65 byte inputs, I am consistently getting wrong outputs.

Hex input: 12EDA9FE8DFCDD25D5430EA64229D04F6B41B2E5A1587C29CD499A63EB79D117113076A02B73D130FB904C9E91075FCD16F735C6850DFADB125EB826D96A113F09

Expected output: a57120a3aef5d9df892cf1a6c2858107a98739f9bb6a7794e42d401491286d17

Actual output: 4FB64EDF838DDA7F47336E0791409B30D871CF26D838F7760EE6E15F7BFD44B7

Website to check: https://moneroaddress.org (Use Ctrl + Shift + I, console, this.cn_fast_hash("hex string here"))

**Comment by ligi** [comment] 2018-06-01 21:24
I think this is a duplicate of #3 - currently I am using keccak_shortcut from kethereum which currently redirects to the bouncycastle implementation - will switch to this pure kotlin keccak when #3 is solved - recently seen @romus making some commits in a branch for this bug - so hopefully soon

**Closed as completed by ligi** 2018-06-01 21:24 UTC

**Comment by svegaxmr** [comment] 2018-06-01 21:33
I have fixed this by transcribing romus' keccak256 branch from java

**Comment by ligi** [comment] 2018-06-01 21:36
Interesting - can you elaborate? Thought @romus is not yet finished as this change is not yet on master

**Comment by ligi** [comment] 2018-06-03 18:06
@svegaxmr be careful with this - I uncovered another problem with the implementation: https://github.com/romus/sha/issues/4 - just as a warning as it sounds you use it currently

**Comment by ligi** [comment] 2018-06-03 19:43
@svegaxmr this repo now also contains the changes and a fix for the bug I found

**Comment by ligi** [comment] 2018-06-04 07:49
@svegaxmr - this lib should be ready to use now - also now tested against the Nist test vectors - so should be ready for usage ..-)
